# Generated by Django 6.0.3 on 2026-03-04 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('planned_effort_hours', models.FloatField()),
                ('is_rescheduled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_effort_hours', models.FloatField()),
                ('completed_flag', models.BooleanField(default=False)),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.scheduleentry')),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('deadline_date', models.DateField()),
                ('estimated_effort_hours', models.FloatField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.studyplan')),
            ],
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.task'),
        ),
    ]
